# Generated by Django 4.0.6 on 2022-10-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('my_id', models.AutoField(primary_key=True, serialize=False)),
                ('snippet', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
