# Generated by Django 4.0.6 on 2022-10-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='name',
            field=models.CharField(default='', max_length=122),
        ),
    ]
