# Generated by Django 4.0.6 on 2022-10-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullapp', '0002_data_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='my_id',
        ),
        migrations.AddField(
            model_name='data',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
